### ISSUE TITLE
License

### ISSUE THREAD

**Issue by htv04** [TheV360/Love2DSmileBASICLibrary#5]
Okay, this library is amazing. I'm definitely considering using this library for some projects I want to work on, but I have one issue with it: the license.

Currently, the license is basically "don't take credit for this," and that's it. It doesn't specify things like whether it's okay to use it in one's projects, modifications are allowed, or if it can be used commercially.

I feel that a much better license for this would be the MIT license, because it basically entails the same message (along with some other restrictions, like having to include the license with derivative works), but also reassures developers that the code in this project can be used freely.

**Comment by TheV360** [comment]
very fast turnaround on these issues, hah. apologies. but done!.. some mistakes remain in the README.MD, but it should be easy enough to figure out -- i did remove `text.png` just to be safe.

**Comment by htv04** [comment]
No worries, thanks for licensing this 👍
